name: Deploy To-Do App to GitHub Pages

on:
  push:
    branches:
      - main # or 'main', depending on which branch you decided to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: # <--- ADD THIS BLOCK
      contents: write # Allows the bot to write to the repository
      pages: write # Allows the bot to deploy to GitHub Pages
      id-token: write # Required for some OIDC configurations, good practice for Pages

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies (if needed)
        run: npm install

      - name: Build or copy files
        run: |
          mkdir public
          cp -r src/* public/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
